development:
  url: {{envOr "DATABASE_URL" "postgres://dillon@127.0.0.1:5432/budgetal_development?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/budgetal_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/budgetal_production?sslmode=disable"}}