development:
  url: {{envOr "DATABASE_URL" "postgres://localhost:5432/budgetal_go_development?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://localhost:5432/budgetal_go_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres:///budgetal_go_production?host=/var/run/postgresql"}}
