development:
  url: {{envOr "DATABASE_URL" "postgres:///budgetal_go_development?host=/var/run/postgresql"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres:///budgetal_go_test?host=/var/run/postgresql"}}

production:
  url: {{envOr "DATABASE_URL" "postgres:///budgetal_go_production?host=/var/run/postgresql"}}
