# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/airbrake/gobrake"
  version = "3.7.4"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.15"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.6.0"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.14.3"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/mw-paramlogger"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.2.0"

[[constraint]]
  name = "github.com/gobuffalo/plush"
  version = "3.8.0"

[[constraint]]
  name = "github.com/gobuffalo/pop"
  version = "4.10.0"

[[constraint]]
  name = "github.com/gobuffalo/suite"
  version = "2.6.2"

[[constraint]]
  name = "github.com/gobuffalo/uuid"
  version = "2.0.5"

[[constraint]]
  name = "github.com/gobuffalo/validate"
  version = "2.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/x"

[[constraint]]
  name = "github.com/markbates/grift"
  version = "1.0.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gobuffalo/httptest"
  version = "1.2.0"
